alipay:
  appId: 2021000148641490
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCEkAz9620vmTk6CVYuKUVIYBqZxdPZpli17b2wwe0m/gTlldr3b2qtBisGEpCmkPa4z3wQeB7h0FkZ8nmBr99kb+cTRvwSIiFK13moskDsFPCmtwlA04K0sO4iAWuI2w6L3Nlbo9ehUV7OOlmDDu9rEcqtU77kaUk5pOKkw2j8D7NoTrhvy0jMvH1zSjjD2jbfSrdOJHv9vIjjaSXTbi3kcAIY99shet7jRsNO2+qwGfRFf3R1bHKPaqTGE3faccWQbzqrmUbTEFxJa+kgm+XvPUYTRo9XWUZYeu88pYbTiQtPyrpX315p3FiUWXiINXIJIayGDIRLAge8xk/hQkOfAgMBAAECggEAcXKym7Ca3ex8zE1nQtQxJfKRcV6bop45N2GCQL6GjiNA35bzMWVZ3z/zHBxRTSus6pcvLw0OKOVdC9a25CU2wsb99EKAwagR4/IqfRQoeaKmHZdxxNf++VKeSd37QMFwXoQgRMwgYz+3KjlHl+D1RyWP1exg5yuv7jRNfwJ5W5V63S4qTXuJnvG3wUTCrrfswCJKcLlWHQCCXFKiByn9RPfEtIY9GCEWbL2/BgiwcD4WdXnMI0x2masCq86C0R6gggJyj6nV3DtdJMwOlNBVp8Z8anPeAj6vRuDvOALiTg58VcOVrtB/X17KxtglBTAWF812+/uEkLz6203+PM9f0QKBgQDO4+LDtp787mIGi9C25PEn48yao07JQGyylChUkSZL2sp/CKiKFs994gvM8TMLqYl2xNY3JbTpceP0JnhteOW+ySwWBgTcHOKix3928ns8l75agsGr1jTiDVX5F21IYhxmOK/WijialKHTLg43fhcqbRUkMamhG2YaFLrGjfOPSQKBgQCkB4AOGkew6DhNQTKyRyXgTXohFxC6wetDzw3/GXdmegi2+1GWN5O/L6YbUK8+06tuKfErsCPwZ9uve7OjtTyU0VFV7EG3wLZK3y5mIq9niYeHE4vWi7lDru77s0/GtQJuU4FaRgDIMBqTGneMCN3+i03ubDW3XNNT2u79E/JzpwKBgHGkregxhS2MSB4uaMw9/9WYhMggkmNr1wlU5r5lKLMcEIUtHV8U3o7YPwEpMI/kZZTu1HhgZvqgS8XN5/LCKPjeii/iyIKb/0XI7dRJp7YF6FLRZk7ckBnnl2UHIElVUyI3Wycur58Bq85Tiw2iXlk4qBdEjFfps/D5mAr+6F25AoGALBSH6UJOuc/uMXSv9xD/sMOhansUV9v9KX/fNwrU94kcBnCLgF73KY3YicapEa04iKZk1WTEg7qlYwdPQ1NVMHj/7qNLFeKIGp7XjUMM+DoRXc926PUrmHDOcH3DlpbWTGfMf0IIu8ORoK6gKdXIMruk+cnCtcAQWpyfVQujQEkCgYAgfa2ZnPtTrT6gIyNPqg7Ybxesj16wQB/UlUii1k1qXrdfuevbXGpkG8gn46ta8KJkjyxZ65/zmk1lYokhlGkEEkdNq6MZck3piF0xjcYe3cKXElnjBX6lFU6QkaneKVs4EbNXBq6z5iEVHm8KwJWmL+In154qreM8Y0Csn+idsQ==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvhQJRaaEG4mD6Xm7stg1k4EkCanXFWAMl8/oNyiVGRnscIL5mRMBlT++8CLSWexJBOx1a59TyS5r4khdyIP/KGdX34uDXRkr7PjP+JJ0Q7UFNoK1Mp6jDvvSSmllcVnn7sdauo0UBPPwWI68ICe1u3GKg30f5l2X6hSCXDxujy9CCiiQUyeuxp9eqMStcTkYCBkNAqP0ARk2btCJx4fXQ8PjHVu3bXU4Ax4w4VQekba7O+tbyl8PqmzhN0Hwcv7GHvEEklvFgSG3errCyyx6A9h/limic6ncQoa/Jd7uEmB4y4O5aUwut59EEGt9k1dG40mpkjpJYA+3AdLokVpF2wIDAQAB
  notifyUrl: http://rbe6864f.natappfree.cc/alipay/notify
  returnUrl: http://rbe6864f.natappfree.cc/alipay/return
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

# 数据源配置
spring:
  application:
    name: ershou
  datasource:
    url: jdbc:mysql://localhost:3306/ershou?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 1800000
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 日志配置
logging:
  level:
    com:
      xuchao:
        ershou: debug
        ershou.service.impl.BaiduImageAuditServiceImpl: DEBUG
    com.baidu.aip: DEBUG

# JWT配置
jwt:
  secret: your_secret_key_at_least_32_bytes_long_1234567896846486464864864856456560
  expiration: 86400000

# 文件上传路径
file:
  upload:
    path: E:/upload/images
    url:
      prefix: http://${file.server.ip}:${file.server.port}/images
  server:
    ip: 192.168.0.103
    port: 8080

# 阿里云短信服务配置
aliyun:
  sms:
    accessKeyId: your_access_key_id
    accessKeySecret: your_access_key_secret
    signName: your_sign_name
    templateCode:
      register: SMS_123456789
      forgetPassword: SMS_123456790
      paymentPassword: SMS_123456791

# 百度AI内容审核配置
baidu:
  ai:
    appId: 118810361
    apiKey: JRUFMLoMX4OXH0eWsUENQ8wr
    secretKey: qE4yQ9sQaWBchWV7Dr1lbCmQ0aKICdh4
    mock: false 